### ISSUE TITLE
Issue filing UX/UI styling and behavior[BUG] 

### ISSUE THREAD

**Issue by cheade** [microsoft/accessibility-insights-windows#546]
**Describe the bug**
Button UX behavior and styling in the issue filing for Azure Boards section. 
Text box behavior in GitHub Issue filing has primary text color instead of placeholder text (secondary-text), making it look like text is already filled in. 

**To Reproduce**
1. Run automated checks on an app with errors
2. Click file issue (make sure you don't have a service connected, this should be a first-time setup)
3. Button to connect Azure Boards account is blue before any text has been entered.
4. Text box in GitHub has stand-in text that is primary colored, making it look like there is already text in the box. 

**Expected behavior**
Azure Boards Issue filing setup: 
Button should be disabled styling until a user enters in text to submit. 
GitHub textbox: placeholder text should be in secondary-text color (see placeholder text in the Azure Boards section)

**Screenshots or .GIF**
Azure Boards: 
![image](https://user-images.githubusercontent.com/40274682/64979923-a010c800-d86d-11e9-9bcd-a74d9f393460.png)
GitHub: 
![image](https://user-images.githubusercontent.com/40274682/64979944-ab63f380-d86d-11e9-877f-4a3b455b993c.png)

**Desktop (please complete the following information):**
- OS: Windows 10 version 1809 (OS Build 17763.437)
- Accessibility Insights for Windows Version: Prerelease Build (1.1.988.1)
- Target Application: Wildlife manager
- Target Application Version: N/A

**Additional context**
Priority requested - low
[Link to Figma file](https://www.figma.com/file/MxXdGGjWOjE7KaL3rfJNed5C/Accessibility-Insights-for-Desktop?node-id=442%3A3)

**Comment by ferBonnin** [comment]
Marking as help wanted, this should be a straightforward fix.

**Comment by DaveTryon** [comment]
@cheade, please regress this against a current canary build and close if it's fixed to your satisfaction. Thanks!

**Comment by cheade** [comment]
Thanks, @DaveTryon ! It looks like the GItHub Text color has been resolved but the button for Connecting the Azure DevOps account is still in its primary color. It should be disabled or not present until a user inputs the data into the text field.

**Comment by ferBonnin** [comment]
assigning Dave and marking as Active since per Chelsea, the button is still not using expected behaviour

**Comment by risanaka** [comment]
By the way, looking at 1.1.1025.1, the text field section for Azure Board and GitHub are slightly misaligned vertically (when you toggle between the two, it's a bit more evident, but here's a screenshot):

![image](https://user-images.githubusercontent.com/144273/67694482-a14f0d80-f960-11e9-98af-c8baf35277b9.png)

Also (including here since I'm not sure if it's a regression--let me know if I should split it out into a separate bug):
1. Go to **Settings > Connections**.
1. Select **GitHub**.
1. Go to **Contrast**.
1. Go to **Settings > Connections**.

Expected:
Either: Azure Boards is selected, and its text field is visible, or, none of the options are selected, and the text field is not visible (I think is the default behavior?)

Actual:
GitHub radio button option is not selected, and the GitHub text field is visible:
![image](https://user-images.githubusercontent.com/144273/67694687-03a80e00-f961-11e9-9af6-4734295198b2.png)

**Comment by cheade** [comment]
Second part of issue has been resolved. Bug created for first part of issue:
#643
